export { default as HomePage } from './HomePage';
export { default as HotelsPage } from './HotelsPage';
export { default as LoginPage } from './LoginPage';
export { default as NewOrderPage } from './NewOrderPage';
export { default as NotFoundPage } from './NotFoundPage';
export { default as OrderPage } from './OrderPage';
export { default as OrdersPage } from './OrdersPage';
export { default as ViewOrderAgencyPage } from './ViewOrderAgencyPage';
export { default as ViewOrderPage } from './ViewOrderPage';
