import styled from 'styled-components';

import { ReactComponent as AddSvg } from 'assets/icons/add.svg';
import { ReactComponent as ArrowLeftSvg } from 'assets/icons/arrow-left.svg';
import { ReactComponent as CalendarSvg } from 'assets/icons/calendar.svg';
import { ReactComponent as CheckSvg } from 'assets/icons/check.svg';
import { ReactComponent as CircleArrowSvg } from 'assets/icons/circle-arrow.svg';
import { ReactComponent as CloseSvg } from 'assets/icons/close.svg';
import { ReactComponent as CornerDownSvg } from 'assets/icons/corner-down.svg';
import { ReactComponent as DeleteSvg } from 'assets/icons/delete.svg';
import { ReactComponent as DocumentSvg } from 'assets/icons/document.svg';
import { ReactComponent as DotsSvg } from 'assets/icons/dots.svg';
import { ReactComponent as EditSvg } from 'assets/icons/edit.svg';
import { ReactComponent as GoArrowSvg } from 'assets/icons/go-arrow.svg';
import { ReactComponent as ImageErrorSvg } from 'assets/icons/image-error.svg';
import { ReactComponent as LocationSvg } from 'assets/icons/location.svg';
import { ReactComponent as LogoSvg } from 'assets/icons/logo.svg';
import { ReactComponent as MessageSvg } from 'assets/icons/message.svg';
import { ReactComponent as NoPhotoSvg } from 'assets/icons/no-photo.svg';
import { ReactComponent as PenSvg } from 'assets/icons/pen.svg';
import { ReactComponent as PlusSvg } from 'assets/icons/plus.svg';
import { ReactComponent as SearchSvg } from 'assets/icons/search.svg';
import { ReactComponent as SortSvg } from 'assets/icons/sort.svg';
import { ReactComponent as StarSvg } from 'assets/icons/star.svg';
import { ReactComponent as SuccessSvg } from 'assets/icons/success.svg';
import { ReactComponent as SuccessSmallSvg } from 'assets/icons/success-small.svg';

export const Add = styled(AddSvg)``;
export const ArrowLeft = styled(ArrowLeftSvg)``;
export const Calendar = styled(CalendarSvg)``;
export const Check = styled(CheckSvg)``;
export const CircleArrow = styled(CircleArrowSvg)``;
export const Close = styled(CloseSvg)``;
export const CornerDown = styled(CornerDownSvg)``;
export const Delete = styled(DeleteSvg)``;
export const Document = styled(DocumentSvg)``;
export const Dots = styled(DotsSvg)``;
export const Edit = styled(EditSvg)``;
export const GoArrow = styled(GoArrowSvg)``;
export const ImageError = styled(ImageErrorSvg)``;
export const Location = styled(LocationSvg)``;
export const Logo = styled(LogoSvg)``;
export const Message = styled(MessageSvg)``;
export const NoPhoto = styled(NoPhotoSvg)``;
export const Pen = styled(PenSvg)``;
export const Plus = styled(PlusSvg)``;
export const Search = styled(SearchSvg)``;
export const Sort = styled(SortSvg)``;
export const Star = styled(StarSvg)``;
export const Success = styled(SuccessSvg)``;
export const SuccessSmall = styled(SuccessSmallSvg)``;
